import type { InsertGiftProduct } from "@shared/schema";

export const seedGiftProducts: InsertGiftProduct[] = [
  // Technology - Budget: Low to Premium
  {
    name: "Wireless Earbuds",
    description: "High-quality wireless earbuds with noise cancellation and long battery life",
    category: "Technology",
    priceMin: 1500,
    priceMax: 3000,
    interests: ["Technology", "Music"],
    occasions: ["Birthday", "Anniversary", "Graduation", "Just Because"],
    relationship: ["friend", "partner", "family", "colleague"],
    personality: ["modern", "tech-savvy", "minimalist"],
    affiliateLink: "https://example.com/wireless-earbuds",
    imageUrl: null,
    tags: ["audio", "bluetooth", "portable"]
  },
  {
    name: "Portable Power Bank 20000mAh",
    description: "Fast-charging portable charger with dual USB ports",
    category: "Technology",
    priceMin: 800,
    priceMax: 1500,
    interests: ["Technology", "Travel"],
    occasions: ["Birthday", "Just Because"],
    relationship: ["friend", "colleague", "family"],
    personality: ["practical", "tech-savvy"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["charging", "portable", "travel"]
  },
  {
    name: "Smart Watch Fitness Tracker",
    description: "Feature-rich smartwatch with heart rate monitoring and fitness tracking",
    category: "Technology",
    priceMin: 3000,
    priceMax: 8000,
    interests: ["Technology", "Fitness", "Sports"],
    occasions: ["Birthday", "Anniversary", "Graduation"],
    relationship: ["partner", "family", "friend"],
    personality: ["health-conscious", "tech-savvy", "active"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["wearable", "fitness", "smart"]
  },
  {
    name: "LED Desk Lamp with USB Charging",
    description: "Adjustable LED lamp with phone charging port, perfect for work or study",
    category: "Technology",
    priceMin: 600,
    priceMax: 1200,
    interests: ["Technology"],
    occasions: ["Birthday", "Graduation", "Just Because"],
    relationship: ["friend", "colleague", "family"],
    personality: ["practical", "studious"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["lighting", "desk", "functional"]
  },

  // Books - Budget: Low to Medium
  {
    name: "Bestselling Fiction Novel Set",
    description: "Collection of award-winning contemporary fiction novels",
    category: "Books",
    priceMin: 500,
    priceMax: 1500,
    interests: ["Books", "Art"],
    occasions: ["Birthday", "Just Because", "Holiday"],
    relationship: ["friend", "family", "partner"],
    personality: ["thoughtful", "creative", "intellectual"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["reading", "fiction", "collection"]
  },
  {
    name: "Personal Development Book Bundle",
    description: "Inspiring self-help and personal growth books",
    category: "Books",
    priceMin: 400,
    priceMax: 1000,
    interests: ["Books"],
    occasions: ["Birthday", "Graduation", "Just Because"],
    relationship: ["friend", "colleague", "family"],
    personality: ["ambitious", "thoughtful", "growth-minded"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["self-help", "inspiration", "learning"]
  },
  {
    name: "Coffee Table Art Book",
    description: "Beautiful photography or art book perfect for display",
    category: "Books",
    priceMin: 800,
    priceMax: 2000,
    interests: ["Books", "Art", "Photography"],
    occasions: ["Birthday", "Anniversary"],
    relationship: ["partner", "family", "friend"],
    personality: ["artistic", "sophisticated", "cultured"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["art", "photography", "decorative"]
  },

  // Music - Budget: Low to High
  {
    name: "Vinyl Record Player",
    description: "Vintage-style turntable with modern Bluetooth connectivity",
    category: "Music",
    priceMin: 4000,
    priceMax: 8000,
    interests: ["Music"],
    occasions: ["Birthday", "Anniversary", "Graduation"],
    relationship: ["partner", "family", "friend"],
    personality: ["vintage", "music-lover", "nostalgic"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["vinyl", "audio", "retro"]
  },
  {
    name: "Guitar Capo and Picks Set",
    description: "Essential accessories for acoustic guitar players",
    category: "Music",
    priceMin: 200,
    priceMax: 500,
    interests: ["Music"],
    occasions: ["Birthday", "Just Because"],
    relationship: ["friend", "family"],
    personality: ["creative", "artistic", "musical"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["guitar", "accessories", "musical"]
  },
  {
    name: "Bluetooth Portable Speaker",
    description: "Waterproof portable speaker with premium sound quality",
    category: "Music",
    priceMin: 1500,
    priceMax: 3500,
    interests: ["Music", "Travel", "Technology"],
    occasions: ["Birthday", "Just Because"],
    relationship: ["friend", "partner", "family"],
    personality: ["outgoing", "music-lover", "social"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["audio", "portable", "bluetooth"]
  },

  // Art & Crafts - Budget: Free (DIY) to Medium
  {
    name: "DIY Scrapbook Kit",
    description: "Complete scrapbooking kit with papers, stickers, and embellishments",
    category: "Art",
    priceMin: 0,
    priceMax: 0,
    interests: ["Art", "DIY/Crafts"],
    occasions: ["Birthday", "Anniversary", "Just Because"],
    relationship: ["partner", "friend", "family"],
    personality: ["creative", "sentimental", "thoughtful"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["diy", "handmade", "memories"]
  },
  {
    name: "Watercolor Painting Set",
    description: "Professional watercolor paints with brushes and paper",
    category: "Art",
    priceMin: 800,
    priceMax: 2000,
    interests: ["Art", "DIY/Crafts"],
    occasions: ["Birthday", "Graduation", "Just Because"],
    relationship: ["friend", "family"],
    personality: ["creative", "artistic", "expressive"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["painting", "art-supplies", "creative"]
  },
  {
    name: "Adult Coloring Book Set",
    description: "Intricate coloring books with premium colored pencils",
    category: "Art",
    priceMin: 400,
    priceMax: 900,
    interests: ["Art"],
    occasions: ["Birthday", "Just Because"],
    relationship: ["friend", "family", "colleague"],
    personality: ["relaxed", "creative", "mindful"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["coloring", "relaxation", "art"]
  },

  // Sports & Fitness - Budget: Low to High
  {
    name: "Yoga Mat with Carrying Strap",
    description: "Non-slip yoga mat with alignment markers",
    category: "Sports",
    priceMin: 600,
    priceMax: 1500,
    interests: ["Fitness", "Sports"],
    occasions: ["Birthday", "Just Because"],
    relationship: ["friend", "family", "colleague"],
    personality: ["health-conscious", "active", "mindful"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["yoga", "fitness", "exercise"]
  },
  {
    name: "Resistance Bands Set",
    description: "Complete resistance training bands with different strengths",
    category: "Sports",
    priceMin: 400,
    priceMax: 1000,
    interests: ["Fitness", "Sports"],
    occasions: ["Birthday", "Just Because"],
    relationship: ["friend", "family", "colleague"],
    personality: ["active", "health-conscious", "dedicated"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["fitness", "training", "portable"]
  },
  {
    name: "Premium Sports Duffle Bag",
    description: "Spacious gym bag with shoe compartment and water bottle holder",
    category: "Sports",
    priceMin: 1200,
    priceMax: 2500,
    interests: ["Sports", "Fitness"],
    occasions: ["Birthday", "Graduation"],
    relationship: ["friend", "family", "partner"],
    personality: ["active", "organized", "athletic"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["gym", "bag", "storage"]
  },
  {
    name: "Football/Soccer Ball",
    description: "Professional-quality football for outdoor play",
    category: "Sports",
    priceMin: 500,
    priceMax: 1500,
    interests: ["Sports"],
    occasions: ["Birthday", "Just Because"],
    relationship: ["friend", "family"],
    personality: ["active", "competitive", "social"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["sports", "outdoor", "team"]
  },

  // Travel - Budget: Low to Premium
  {
    name: "Travel Adapter Universal Kit",
    description: "All-in-one travel adapter for international trips",
    category: "Travel",
    priceMin: 500,
    priceMax: 1200,
    interests: ["Travel", "Technology"],
    occasions: ["Birthday", "Graduation", "Just Because"],
    relationship: ["friend", "family", "colleague"],
    personality: ["adventurous", "practical", "explorer"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["travel", "adapter", "international"]
  },
  {
    name: "Travel Backpack 40L",
    description: "Durable backpack with laptop compartment for travelers",
    category: "Travel",
    priceMin: 2000,
    priceMax: 4000,
    interests: ["Travel"],
    occasions: ["Birthday", "Graduation"],
    relationship: ["friend", "family", "partner"],
    personality: ["adventurous", "practical", "nomadic"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["backpack", "luggage", "travel"]
  },
  {
    name: "Travel Journal & Pen Set",
    description: "Leather-bound travel journal with quality pens",
    category: "Travel",
    priceMin: 600,
    priceMax: 1500,
    interests: ["Travel", "Books"],
    occasions: ["Birthday", "Graduation", "Just Because"],
    relationship: ["friend", "family", "partner"],
    personality: ["thoughtful", "adventurous", "creative"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["journal", "writing", "memories"]
  },
  {
    name: "Scratch-Off World Map",
    description: "Interactive world map to track travel adventures",
    category: "Travel",
    priceMin: 400,
    priceMax: 1000,
    interests: ["Travel"],
    occasions: ["Birthday", "Just Because"],
    relationship: ["friend", "family", "partner"],
    personality: ["adventurous", "explorer", "goal-oriented"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["map", "decorative", "interactive"]
  },

  // Cooking & Food - Budget: Low to High
  {
    name: "Stainless Steel Cookware Set",
    description: "Professional-grade pots and pans set",
    category: "Cooking",
    priceMin: 3000,
    priceMax: 6000,
    interests: ["Cooking", "Food"],
    occasions: ["Birthday", "Anniversary"],
    relationship: ["partner", "family"],
    personality: ["culinary", "home-chef", "practical"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["cookware", "kitchen", "professional"]
  },
  {
    name: "Spice Gift Set Gourmet",
    description: "Collection of exotic spices and seasonings",
    category: "Cooking",
    priceMin: 800,
    priceMax: 1800,
    interests: ["Cooking", "Food"],
    occasions: ["Birthday", "Holiday", "Just Because"],
    relationship: ["friend", "family", "colleague"],
    personality: ["culinary", "adventurous", "foodie"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["spices", "gourmet", "seasoning"]
  },
  {
    name: "Chef's Knife Premium",
    description: "Professional chef's knife with ergonomic handle",
    category: "Cooking",
    priceMin: 1500,
    priceMax: 3500,
    interests: ["Cooking", "Food"],
    occasions: ["Birthday", "Anniversary", "Graduation"],
    relationship: ["partner", "family", "friend"],
    personality: ["culinary", "serious", "professional"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["knife", "kitchen", "professional"]
  },
  {
    name: "Recipe Book: Indian Cuisine",
    description: "Comprehensive cookbook for authentic Indian dishes",
    category: "Cooking",
    priceMin: 400,
    priceMax: 900,
    interests: ["Cooking", "Food", "Books"],
    occasions: ["Birthday", "Just Because"],
    relationship: ["friend", "family", "colleague"],
    personality: ["culinary", "traditional", "curious"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["cookbook", "recipes", "indian"]
  },
  {
    name: "Gourmet Chocolate Gift Box",
    description: "Premium assorted chocolates in elegant packaging",
    category: "Food",
    priceMin: 600,
    priceMax: 1500,
    interests: ["Food"],
    occasions: ["Birthday", "Anniversary", "Holiday", "Just Because"],
    relationship: ["partner", "family", "friend", "colleague"],
    personality: ["sweet-tooth", "appreciative", "indulgent"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["chocolate", "gourmet", "gift-box"]
  },

  // Gaming - Budget: Low to Premium
  {
    name: "Gaming Mouse RGB",
    description: "High-precision gaming mouse with customizable RGB lighting",
    category: "Gaming",
    priceMin: 1000,
    priceMax: 2500,
    interests: ["Gaming", "Technology"],
    occasions: ["Birthday", "Just Because"],
    relationship: ["friend", "family"],
    personality: ["gamer", "tech-savvy", "competitive"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["gaming", "mouse", "rgb"]
  },
  {
    name: "Gaming Headset with Mic",
    description: "Immersive gaming headset with noise-cancelling microphone",
    category: "Gaming",
    priceMin: 1500,
    priceMax: 4000,
    interests: ["Gaming", "Technology"],
    occasions: ["Birthday", "Graduation"],
    relationship: ["friend", "family", "partner"],
    personality: ["gamer", "competitive", "social"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["gaming", "headset", "audio"]
  },
  {
    name: "Board Game Strategy Set",
    description: "Collection of popular strategy board games",
    category: "Gaming",
    priceMin: 1200,
    priceMax: 3000,
    interests: ["Gaming"],
    occasions: ["Birthday", "Holiday"],
    relationship: ["friend", "family"],
    personality: ["strategic", "social", "competitive"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["board-game", "strategy", "multiplayer"]
  },
  {
    name: "PlayStation/Xbox Gift Card",
    description: "Digital gift card for game purchases",
    category: "Gaming",
    priceMin: 500,
    priceMax: 5000,
    interests: ["Gaming", "Technology"],
    occasions: ["Birthday", "Holiday", "Just Because"],
    relationship: ["friend", "family"],
    personality: ["gamer", "tech-savvy"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["gift-card", "digital", "gaming"]
  },

  // Fashion - Budget: Low to Premium
  {
    name: "Designer Sunglasses",
    description: "Stylish UV-protection sunglasses",
    category: "Fashion",
    priceMin: 1500,
    priceMax: 5000,
    interests: ["Fashion"],
    occasions: ["Birthday", "Anniversary"],
    relationship: ["partner", "family", "friend"],
    personality: ["stylish", "fashion-forward", "trendy"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["sunglasses", "accessory", "designer"]
  },
  {
    name: "Leather Wallet Premium",
    description: "Genuine leather wallet with RFID protection",
    category: "Fashion",
    priceMin: 1000,
    priceMax: 2500,
    interests: ["Fashion"],
    occasions: ["Birthday", "Anniversary", "Graduation"],
    relationship: ["partner", "family", "friend"],
    personality: ["sophisticated", "practical", "professional"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["wallet", "leather", "accessory"]
  },
  {
    name: "Silk Scarf Luxury",
    description: "Hand-printed silk scarf with elegant patterns",
    category: "Fashion",
    priceMin: 1200,
    priceMax: 3000,
    interests: ["Fashion", "Art"],
    occasions: ["Birthday", "Anniversary"],
    relationship: ["partner", "family", "friend"],
    personality: ["elegant", "sophisticated", "artistic"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["scarf", "silk", "accessory"]
  },
  {
    name: "Watch Minimalist Design",
    description: "Elegant minimalist watch with leather strap",
    category: "Fashion",
    priceMin: 2000,
    priceMax: 6000,
    interests: ["Fashion"],
    occasions: ["Birthday", "Anniversary", "Graduation"],
    relationship: ["partner", "family", "friend"],
    personality: ["minimalist", "sophisticated", "professional"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["watch", "timepiece", "accessory"]
  },

  // Photography - Budget: Medium to Premium
  {
    name: "DSLR Camera Lens 50mm",
    description: "Prime lens perfect for portraits and low-light photography",
    category: "Photography",
    priceMin: 8000,
    priceMax: 15000,
    interests: ["Photography", "Art"],
    occasions: ["Birthday", "Graduation"],
    relationship: ["family", "partner", "friend"],
    personality: ["creative", "artistic", "professional"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["lens", "camera", "photography"]
  },
  {
    name: "Camera Tripod Professional",
    description: "Sturdy tripod with ball head for stable photography",
    category: "Photography",
    priceMin: 1500,
    priceMax: 4000,
    interests: ["Photography"],
    occasions: ["Birthday", "Just Because"],
    relationship: ["friend", "family"],
    personality: ["creative", "detail-oriented", "professional"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["tripod", "camera", "stable"]
  },
  {
    name: "Photo Editing Software License",
    description: "Professional photo editing software subscription",
    category: "Photography",
    priceMin: 3000,
    priceMax: 6000,
    interests: ["Photography", "Technology", "Art"],
    occasions: ["Birthday", "Graduation"],
    relationship: ["friend", "family", "partner"],
    personality: ["creative", "tech-savvy", "professional"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["software", "editing", "digital"]
  },
  {
    name: "Instant Camera Polaroid Style",
    description: "Fun instant camera with film pack",
    category: "Photography",
    priceMin: 4000,
    priceMax: 8000,
    interests: ["Photography"],
    occasions: ["Birthday", "Anniversary", "Just Because"],
    relationship: ["partner", "friend", "family"],
    personality: ["fun", "nostalgic", "creative"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["instant", "camera", "polaroid"]
  },

  // Movies & Entertainment - Budget: Low to Medium
  {
    name: "Movie Streaming Service Gift Card",
    description: "Annual subscription to popular streaming platform",
    category: "Movies",
    priceMin: 1500,
    priceMax: 3000,
    interests: ["Movies"],
    occasions: ["Birthday", "Holiday", "Just Because"],
    relationship: ["friend", "family", "colleague"],
    personality: ["entertainment-lover", "homebody", "cinephile"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["streaming", "subscription", "digital"]
  },
  {
    name: "Popcorn Maker Machine",
    description: "Home popcorn maker for movie nights",
    category: "Movies",
    priceMin: 1200,
    priceMax: 2500,
    interests: ["Movies", "Food"],
    occasions: ["Birthday", "Just Because"],
    relationship: ["friend", "family", "partner"],
    personality: ["entertainment-lover", "homebody", "social"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["popcorn", "movies", "entertainment"]
  },
  {
    name: "Classic Movie Collection DVD/Blu-ray",
    description: "Collector's edition of classic films",
    category: "Movies",
    priceMin: 1500,
    priceMax: 4000,
    interests: ["Movies"],
    occasions: ["Birthday", "Anniversary"],
    relationship: ["partner", "family", "friend"],
    personality: ["cinephile", "nostalgic", "collector"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["movies", "collection", "classic"]
  },

  // Nature & Outdoors - Budget: Low to High
  {
    name: "Indoor Plant Terrarium Kit",
    description: "Complete terrarium kit with plants and decorative elements",
    category: "Nature",
    priceMin: 600,
    priceMax: 1500,
    interests: ["Nature", "DIY/Crafts"],
    occasions: ["Birthday", "Just Because"],
    relationship: ["friend", "family", "colleague"],
    personality: ["nature-lover", "nurturing", "zen"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["plants", "indoor", "decorative"]
  },
  {
    name: "Binoculars Bird Watching",
    description: "High-quality binoculars for nature observation",
    category: "Nature",
    priceMin: 2000,
    priceMax: 5000,
    interests: ["Nature"],
    occasions: ["Birthday", "Just Because"],
    relationship: ["family", "friend"],
    personality: ["nature-lover", "observer", "patient"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["binoculars", "bird-watching", "outdoor"]
  },
  {
    name: "Camping Hammock Portable",
    description: "Lightweight hammock perfect for outdoor adventures",
    category: "Nature",
    priceMin: 800,
    priceMax: 2000,
    interests: ["Nature", "Travel"],
    occasions: ["Birthday", "Just Because"],
    relationship: ["friend", "family"],
    personality: ["adventurous", "nature-lover", "relaxed"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["hammock", "camping", "outdoor"]
  },
  {
    name: "Gardening Tool Set",
    description: "Complete gardening toolkit with gloves and organizer",
    category: "Nature",
    priceMin: 700,
    priceMax: 1800,
    interests: ["Nature", "DIY/Crafts"],
    occasions: ["Birthday", "Just Because"],
    relationship: ["family", "friend", "colleague"],
    personality: ["nature-lover", "nurturing", "patient"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["gardening", "tools", "plants"]
  },

  // DIY/Crafts - Budget: Free (DIY) to Medium
  {
    name: "DIY Candle Making Kit",
    description: "Complete kit to make scented candles at home",
    category: "DIY/Crafts",
    priceMin: 0,
    priceMax: 0,
    interests: ["DIY/Crafts"],
    occasions: ["Birthday", "Just Because"],
    relationship: ["friend", "family"],
    personality: ["creative", "crafty", "thoughtful"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["diy", "candles", "handmade"]
  },
  {
    name: "Knitting & Crochet Starter Kit",
    description: "Yarn, needles, and patterns for beginners",
    category: "DIY/Crafts",
    priceMin: 600,
    priceMax: 1500,
    interests: ["DIY/Crafts"],
    occasions: ["Birthday", "Just Because"],
    relationship: ["friend", "family"],
    personality: ["creative", "patient", "crafty"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["knitting", "yarn", "crafts"]
  },
  {
    name: "Wood Carving Tool Set",
    description: "Professional wood carving tools for artisans",
    category: "DIY/Crafts",
    priceMin: 1000,
    priceMax: 2500,
    interests: ["DIY/Crafts", "Art"],
    occasions: ["Birthday", "Graduation"],
    relationship: ["friend", "family"],
    personality: ["creative", "artistic", "detail-oriented"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["woodworking", "carving", "tools"]
  },
  {
    name: "Personalized Photo Frame DIY Kit",
    description: "Materials to create custom decorated photo frames",
    category: "DIY/Crafts",
    priceMin: 0,
    priceMax: 0,
    interests: ["DIY/Crafts"],
    occasions: ["Birthday", "Anniversary", "Just Because"],
    relationship: ["partner", "friend", "family"],
    personality: ["sentimental", "creative", "thoughtful"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["diy", "photo-frame", "handmade"]
  },

  // Fitness - Dedicated Category - Budget: Low to High
  {
    name: "Adjustable Dumbbells Set",
    description: "Space-saving adjustable dumbbells from 2kg to 24kg",
    category: "Fitness",
    priceMin: 3000,
    priceMax: 8000,
    interests: ["Fitness", "Sports"],
    occasions: ["Birthday", "Just Because"],
    relationship: ["friend", "family", "partner"],
    personality: ["active", "health-conscious", "dedicated"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["weights", "strength", "home-gym"]
  },
  {
    name: "Fitness Tracker Smart Band",
    description: "Activity tracker with step counter and sleep monitoring",
    category: "Fitness",
    priceMin: 1500,
    priceMax: 4000,
    interests: ["Fitness", "Technology"],
    occasions: ["Birthday", "Just Because"],
    relationship: ["friend", "family", "colleague"],
    personality: ["health-conscious", "data-driven", "active"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["tracker", "wearable", "health"]
  },
  {
    name: "Foam Roller Muscle Recovery",
    description: "High-density foam roller for post-workout recovery",
    category: "Fitness",
    priceMin: 500,
    priceMax: 1200,
    interests: ["Fitness", "Sports"],
    occasions: ["Birthday", "Just Because"],
    relationship: ["friend", "family"],
    personality: ["active", "health-conscious", "recovery-focused"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["recovery", "foam-roller", "massage"]
  },
  {
    name: "Protein Shaker Bottle with Storage",
    description: "Premium shaker bottle with supplement storage compartments",
    category: "Fitness",
    priceMin: 300,
    priceMax: 800,
    interests: ["Fitness"],
    occasions: ["Birthday", "Just Because"],
    relationship: ["friend", "colleague", "family"],
    personality: ["active", "health-conscious", "practical"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["shaker", "protein", "fitness-accessories"]
  },
  {
    name: "Jump Rope Speed Training",
    description: "Professional speed jump rope for cardio workouts",
    category: "Fitness",
    priceMin: 200,
    priceMax: 600,
    interests: ["Fitness", "Sports"],
    occasions: ["Birthday", "Just Because"],
    relationship: ["friend", "family"],
    personality: ["active", "cardio-focused", "athletic"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["jump-rope", "cardio", "training"]
  },
  {
    name: "Kettlebell Set Various Weights",
    description: "Cast iron kettlebells for functional training",
    category: "Fitness",
    priceMin: 2000,
    priceMax: 6000,
    interests: ["Fitness", "Sports"],
    occasions: ["Birthday", "Just Because"],
    relationship: ["friend", "family", "partner"],
    personality: ["active", "strength-focused", "serious"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["kettlebell", "strength", "functional"]
  },
  {
    name: "Pull-up Bar Doorway Mount",
    description: "Adjustable pull-up bar for home workouts",
    category: "Fitness",
    priceMin: 800,
    priceMax: 1800,
    interests: ["Fitness", "Sports"],
    occasions: ["Birthday", "Just Because"],
    relationship: ["friend", "family"],
    personality: ["active", "strength-focused", "home-fitness"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["pull-up", "strength", "home-gym"]
  },
  {
    name: "Yoga Block and Strap Set",
    description: "Cork yoga blocks with cotton strap for proper alignment",
    category: "Fitness",
    priceMin: 400,
    priceMax: 1000,
    interests: ["Fitness"],
    occasions: ["Birthday", "Just Because"],
    relationship: ["friend", "family", "colleague"],
    personality: ["flexible", "mindful", "wellness-focused"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["yoga", "accessories", "alignment"]
  },
  {
    name: "Ab Roller Wheel with Knee Pad",
    description: "Core strengthening ab roller with comfort knee pad",
    category: "Fitness",
    priceMin: 400,
    priceMax: 1000,
    interests: ["Fitness"],
    occasions: ["Birthday", "Just Because"],
    relationship: ["friend", "family"],
    personality: ["active", "core-focused", "dedicated"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["ab-roller", "core", "strength"]
  },
  {
    name: "Gym Gloves Weightlifting",
    description: "Padded weightlifting gloves with wrist support",
    category: "Fitness",
    priceMin: 400,
    priceMax: 1200,
    interests: ["Fitness", "Sports"],
    occasions: ["Birthday", "Just Because"],
    relationship: ["friend", "family"],
    personality: ["active", "strength-focused", "protective"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["gloves", "weightlifting", "protection"]
  },
  {
    name: "Water Bottle Insulated 1L",
    description: "Stainless steel insulated bottle keeps drinks cold 24hrs",
    category: "Fitness",
    priceMin: 500,
    priceMax: 1500,
    interests: ["Fitness", "Sports", "Travel"],
    occasions: ["Birthday", "Just Because"],
    relationship: ["friend", "family", "colleague"],
    personality: ["active", "health-conscious", "practical"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["water-bottle", "hydration", "insulated"]
  },
  {
    name: "Exercise Ball Stability",
    description: "Anti-burst stability ball for core workouts and stretching",
    category: "Fitness",
    priceMin: 500,
    priceMax: 1200,
    interests: ["Fitness"],
    occasions: ["Birthday", "Just Because"],
    relationship: ["friend", "family"],
    personality: ["active", "core-focused", "flexible"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["exercise-ball", "stability", "core"]
  },
  {
    name: "Massage Gun Percussion Therapy",
    description: "Portable percussion massager for muscle recovery",
    category: "Fitness",
    priceMin: 3000,
    priceMax: 8000,
    interests: ["Fitness", "Sports"],
    occasions: ["Birthday", "Anniversary"],
    relationship: ["partner", "family", "friend"],
    personality: ["active", "recovery-focused", "wellness-oriented"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["massage", "recovery", "therapy"]
  },
  {
    name: "Gym Membership Gift Card",
    description: "3-month gym membership voucher",
    category: "Fitness",
    priceMin: 3000,
    priceMax: 6000,
    interests: ["Fitness", "Sports"],
    occasions: ["Birthday", "Graduation", "Just Because"],
    relationship: ["friend", "family"],
    personality: ["active", "health-conscious", "social"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["membership", "gym", "gift-card"]
  },
  {
    name: "Running Shoes Athletic",
    description: "Professional running shoes with cushioned sole",
    category: "Fitness",
    priceMin: 2500,
    priceMax: 6000,
    interests: ["Fitness", "Sports"],
    occasions: ["Birthday", "Graduation"],
    relationship: ["friend", "family", "partner"],
    personality: ["active", "runner", "athletic"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["running", "shoes", "athletic"]
  },
  {
    name: "Workout Bench Adjustable",
    description: "Multi-position workout bench for home gym",
    category: "Fitness",
    priceMin: 4000,
    priceMax: 10000,
    interests: ["Fitness", "Sports"],
    occasions: ["Birthday"],
    relationship: ["family", "partner"],
    personality: ["active", "serious", "home-fitness"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["bench", "weights", "home-gym"]
  },

  // Additional Technology Products
  {
    name: "Wireless Keyboard and Mouse Combo",
    description: "Ergonomic wireless keyboard and mouse set",
    category: "Technology",
    priceMin: 1500,
    priceMax: 3500,
    interests: ["Technology"],
    occasions: ["Birthday", "Graduation", "Just Because"],
    relationship: ["friend", "colleague", "family"],
    personality: ["tech-savvy", "professional", "practical"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["keyboard", "mouse", "wireless"]
  },
  {
    name: "USB Hub Multi-Port",
    description: "7-port USB hub with fast charging capability",
    category: "Technology",
    priceMin: 600,
    priceMax: 1500,
    interests: ["Technology"],
    occasions: ["Birthday", "Just Because"],
    relationship: ["friend", "colleague", "family"],
    personality: ["tech-savvy", "organized", "practical"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["usb", "hub", "connectivity"]
  },
  {
    name: "Webcam HD 1080p",
    description: "High-definition webcam for video calls and streaming",
    category: "Technology",
    priceMin: 2000,
    priceMax: 4500,
    interests: ["Technology"],
    occasions: ["Birthday", "Graduation"],
    relationship: ["friend", "colleague", "family"],
    personality: ["tech-savvy", "professional", "communicative"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["webcam", "video", "streaming"]
  },
  {
    name: "External SSD 1TB",
    description: "Fast portable SSD for data storage and backup",
    category: "Technology",
    priceMin: 4000,
    priceMax: 8000,
    interests: ["Technology"],
    occasions: ["Birthday", "Graduation"],
    relationship: ["friend", "family", "colleague"],
    personality: ["tech-savvy", "organized", "professional"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["storage", "ssd", "backup"]
  },
  {
    name: "Phone Stand Adjustable",
    description: "Desktop phone holder with adjustable angles",
    category: "Technology",
    priceMin: 300,
    priceMax: 800,
    interests: ["Technology"],
    occasions: ["Birthday", "Just Because"],
    relationship: ["friend", "colleague", "family"],
    personality: ["organized", "practical", "tech-savvy"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["phone", "stand", "desk"]
  },
  {
    name: "Laptop Cooling Pad",
    description: "Cooling pad with adjustable fan speed for laptops",
    category: "Technology",
    priceMin: 800,
    priceMax: 1800,
    interests: ["Technology"],
    occasions: ["Birthday", "Just Because"],
    relationship: ["friend", "colleague", "family"],
    personality: ["tech-savvy", "practical", "professional"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["laptop", "cooling", "accessories"]
  },
  {
    name: "Bluetooth Adapter USB",
    description: "USB Bluetooth adapter for desktop computers",
    category: "Technology",
    priceMin: 300,
    priceMax: 700,
    interests: ["Technology"],
    occasions: ["Birthday", "Just Because"],
    relationship: ["friend", "colleague"],
    personality: ["tech-savvy", "practical"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["bluetooth", "adapter", "connectivity"]
  },
  {
    name: "Smart Home Hub Device",
    description: "Voice-controlled smart home hub and speaker",
    category: "Technology",
    priceMin: 4000,
    priceMax: 8000,
    interests: ["Technology"],
    occasions: ["Birthday", "Anniversary"],
    relationship: ["partner", "family", "friend"],
    personality: ["tech-savvy", "modern", "convenient"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["smart-home", "voice", "automation"]
  },
  {
    name: "Cable Organizer Set",
    description: "Cable management system for clean desk setup",
    category: "Technology",
    priceMin: 200,
    priceMax: 600,
    interests: ["Technology"],
    occasions: ["Birthday", "Just Because"],
    relationship: ["friend", "colleague", "family"],
    personality: ["organized", "neat", "practical"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["cable", "organizer", "desk"]
  },
  {
    name: "Tablet Stand Aluminum",
    description: "Premium aluminum stand for tablets and e-readers",
    category: "Technology",
    priceMin: 700,
    priceMax: 1500,
    interests: ["Technology", "Books"],
    occasions: ["Birthday", "Just Because"],
    relationship: ["friend", "family", "colleague"],
    personality: ["organized", "tech-savvy", "reader"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["tablet", "stand", "aluminum"]
  },

  // Additional Books
  {
    name: "Mystery Thriller Book Bundle",
    description: "Collection of bestselling mystery and thriller novels",
    category: "Books",
    priceMin: 600,
    priceMax: 1500,
    interests: ["Books"],
    occasions: ["Birthday", "Holiday", "Just Because"],
    relationship: ["friend", "family"],
    personality: ["curious", "reader", "mystery-lover"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["mystery", "thriller", "novels"]
  },
  {
    name: "Poetry Collection Anthology",
    description: "Curated anthology of contemporary poetry",
    category: "Books",
    priceMin: 400,
    priceMax: 1000,
    interests: ["Books", "Art"],
    occasions: ["Birthday", "Just Because"],
    relationship: ["friend", "family", "partner"],
    personality: ["romantic", "artistic", "thoughtful"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["poetry", "anthology", "literature"]
  },
  {
    name: "Science Fiction Box Set",
    description: "Classic sci-fi series in collector's edition",
    category: "Books",
    priceMin: 1500,
    priceMax: 3000,
    interests: ["Books", "Technology"],
    occasions: ["Birthday", "Graduation"],
    relationship: ["friend", "family"],
    personality: ["imaginative", "tech-savvy", "curious"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["sci-fi", "series", "collection"]
  },
  {
    name: "Cookbook Vegetarian Recipes",
    description: "Comprehensive vegetarian cookbook with 200+ recipes",
    category: "Books",
    priceMin: 500,
    priceMax: 1200,
    interests: ["Books", "Cooking", "Food"],
    occasions: ["Birthday", "Just Because"],
    relationship: ["friend", "family"],
    personality: ["health-conscious", "culinary", "vegetarian"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["cookbook", "vegetarian", "recipes"]
  },
  {
    name: "Graphic Novel Collection",
    description: "Award-winning graphic novels and comic books",
    category: "Books",
    priceMin: 800,
    priceMax: 2000,
    interests: ["Books", "Art"],
    occasions: ["Birthday", "Just Because"],
    relationship: ["friend", "family"],
    personality: ["artistic", "visual", "creative"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["graphic-novel", "comics", "art"]
  },
  {
    name: "Children's Book Collection",
    description: "Classic children's stories illustrated edition",
    category: "Books",
    priceMin: 600,
    priceMax: 1500,
    interests: ["Books"],
    occasions: ["Birthday", "Holiday"],
    relationship: ["family"],
    ageGroup: "child",
    personality: ["imaginative", "curious"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["children", "illustrated", "classic"]
  },
  {
    name: "Business Strategy Books Set",
    description: "Essential business and leadership books",
    category: "Books",
    priceMin: 800,
    priceMax: 2000,
    interests: ["Books"],
    occasions: ["Birthday", "Graduation"],
    relationship: ["colleague", "friend", "family"],
    personality: ["ambitious", "professional", "leader"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["business", "leadership", "strategy"]
  },
  {
    name: "Biography Collection Famous Personalities",
    description: "Inspiring biographies of historical figures",
    category: "Books",
    priceMin: 700,
    priceMax: 1800,
    interests: ["Books"],
    occasions: ["Birthday", "Just Because"],
    relationship: ["friend", "family"],
    personality: ["curious", "inspired", "learner"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["biography", "history", "inspiration"]
  },
  {
    name: "Kindle E-Reader",
    description: "Digital e-reader with built-in light and long battery life",
    category: "Books",
    priceMin: 8000,
    priceMax: 12000,
    interests: ["Books", "Technology"],
    occasions: ["Birthday", "Graduation", "Anniversary"],
    relationship: ["partner", "family", "friend"],
    personality: ["reader", "tech-savvy", "practical"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["e-reader", "digital", "kindle"]
  },
  {
    name: "Book Light Reading Lamp",
    description: "Clip-on LED reading light for books",
    category: "Books",
    priceMin: 300,
    priceMax: 800,
    interests: ["Books"],
    occasions: ["Birthday", "Just Because"],
    relationship: ["friend", "family"],
    personality: ["reader", "practical"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["reading", "light", "accessories"]
  },

  // Additional Music Products
  {
    name: "Ukulele Beginner Set",
    description: "Soprano ukulele with tuner and carry bag",
    category: "Music",
    priceMin: 1500,
    priceMax: 3000,
    interests: ["Music"],
    occasions: ["Birthday", "Just Because"],
    relationship: ["friend", "family"],
    personality: ["musical", "creative", "learner"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["ukulele", "instrument", "beginner"]
  },
  {
    name: "Music Streaming Subscription",
    description: "Annual premium music streaming service",
    category: "Music",
    priceMin: 1200,
    priceMax: 1500,
    interests: ["Music"],
    occasions: ["Birthday", "Just Because"],
    relationship: ["friend", "family", "partner"],
    personality: ["music-lover", "modern"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["streaming", "subscription", "digital"]
  },
  {
    name: "Headphone Stand Wooden",
    description: "Premium wooden headphone display stand",
    category: "Music",
    priceMin: 500,
    priceMax: 1200,
    interests: ["Music", "Technology"],
    occasions: ["Birthday", "Just Because"],
    relationship: ["friend", "family"],
    personality: ["organized", "music-lover", "aesthetic"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["headphone", "stand", "display"]
  },
  {
    name: "Music Production MIDI Keyboard",
    description: "25-key MIDI controller for music production",
    category: "Music",
    priceMin: 3000,
    priceMax: 6000,
    interests: ["Music", "Technology"],
    occasions: ["Birthday", "Graduation"],
    relationship: ["friend", "family"],
    personality: ["creative", "producer", "tech-savvy"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["midi", "music-production", "keyboard"]
  },
  {
    name: "Concert Tickets Gift Voucher",
    description: "Gift voucher for live music concerts",
    category: "Music",
    priceMin: 1000,
    priceMax: 5000,
    interests: ["Music"],
    occasions: ["Birthday", "Anniversary", "Just Because"],
    relationship: ["partner", "friend", "family"],
    personality: ["music-lover", "social", "experiential"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["concert", "tickets", "live-music"]
  },
  {
    name: "Guitar Wall Mount Hanger",
    description: "Wall-mounted guitar display and storage",
    category: "Music",
    priceMin: 300,
    priceMax: 800,
    interests: ["Music"],
    occasions: ["Birthday", "Just Because"],
    relationship: ["friend", "family"],
    personality: ["musical", "organized", "display"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["guitar", "storage", "wall-mount"]
  },
  {
    name: "Harmonica Set with Case",
    description: "Set of harmonicas in different keys with carrying case",
    category: "Music",
    priceMin: 1000,
    priceMax: 2500,
    interests: ["Music"],
    occasions: ["Birthday", "Just Because"],
    relationship: ["friend", "family"],
    personality: ["musical", "portable", "blues-lover"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["harmonica", "instrument", "portable"]
  },
  {
    name: "Microphone USB Studio",
    description: "USB condenser microphone for recording and streaming",
    category: "Music",
    priceMin: 2500,
    priceMax: 6000,
    interests: ["Music", "Technology"],
    occasions: ["Birthday", "Graduation"],
    relationship: ["friend", "family"],
    personality: ["creative", "performer", "tech-savvy"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["microphone", "recording", "usb"]
  },
  {
    name: "Music Theory Workbook",
    description: "Comprehensive music theory learning book",
    category: "Music",
    priceMin: 400,
    priceMax: 1000,
    interests: ["Music", "Books"],
    occasions: ["Birthday", "Just Because"],
    relationship: ["friend", "family"],
    personality: ["musical", "learner", "studious"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["theory", "education", "music"]
  },
  {
    name: "Drum Practice Pad",
    description: "Silent practice pad for drummers",
    category: "Music",
    priceMin: 800,
    priceMax: 2000,
    interests: ["Music"],
    occasions: ["Birthday", "Just Because"],
    relationship: ["friend", "family"],
    personality: ["musical", "drummer", "dedicated"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["drums", "practice", "percussion"]
  },

  // Additional Art Products
  {
    name: "Acrylic Paint Set Professional",
    description: "36-color professional acrylic paint set",
    category: "Art",
    priceMin: 1200,
    priceMax: 2500,
    interests: ["Art", "DIY/Crafts"],
    occasions: ["Birthday", "Graduation"],
    relationship: ["friend", "family"],
    personality: ["artistic", "creative", "painter"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["acrylic", "paint", "professional"]
  },
  {
    name: "Sketch Pad Premium Paper",
    description: "High-quality sketch pad for artists",
    category: "Art",
    priceMin: 300,
    priceMax: 800,
    interests: ["Art"],
    occasions: ["Birthday", "Just Because"],
    relationship: ["friend", "family"],
    personality: ["artistic", "creative", "sketcher"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["sketch", "paper", "drawing"]
  },
  {
    name: "Calligraphy Pen Set",
    description: "Professional calligraphy pens with ink",
    category: "Art",
    priceMin: 800,
    priceMax: 2000,
    interests: ["Art", "Books"],
    occasions: ["Birthday", "Just Because"],
    relationship: ["friend", "family"],
    personality: ["artistic", "detailed", "elegant"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["calligraphy", "pen", "writing"]
  },
  {
    name: "Canvas Panels for Painting",
    description: "Set of stretched canvas panels various sizes",
    category: "Art",
    priceMin: 600,
    priceMax: 1500,
    interests: ["Art"],
    occasions: ["Birthday", "Just Because"],
    relationship: ["friend", "family"],
    personality: ["artistic", "painter", "creative"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["canvas", "painting", "panels"]
  },
  {
    name: "Art Easel Adjustable",
    description: "Wooden easel with adjustable height",
    category: "Art",
    priceMin: 1500,
    priceMax: 3500,
    interests: ["Art"],
    occasions: ["Birthday", "Graduation"],
    relationship: ["friend", "family"],
    personality: ["artistic", "serious", "painter"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["easel", "painting", "studio"]
  },
  {
    name: "Sculpture Clay Modeling Set",
    description: "Polymer clay set with sculpting tools",
    category: "Art",
    priceMin: 700,
    priceMax: 1800,
    interests: ["Art", "DIY/Crafts"],
    occasions: ["Birthday", "Just Because"],
    relationship: ["friend", "family"],
    personality: ["artistic", "3d", "creative"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["sculpture", "clay", "modeling"]
  },
  {
    name: "Oil Painting Starter Kit",
    description: "Complete oil painting set for beginners",
    category: "Art",
    priceMin: 2000,
    priceMax: 4000,
    interests: ["Art"],
    occasions: ["Birthday", "Graduation"],
    relationship: ["friend", "family"],
    personality: ["artistic", "traditional", "painter"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["oil-painting", "starter", "kit"]
  },
  {
    name: "Art Pencil Set Graphite",
    description: "Professional graphite pencils 12-piece set",
    category: "Art",
    priceMin: 500,
    priceMax: 1200,
    interests: ["Art"],
    occasions: ["Birthday", "Just Because"],
    relationship: ["friend", "family"],
    personality: ["artistic", "sketcher", "detailed"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["pencil", "graphite", "drawing"]
  },
  {
    name: "Watercolor Brush Set",
    description: "Professional watercolor brushes various sizes",
    category: "Art",
    priceMin: 600,
    priceMax: 1500,
    interests: ["Art"],
    occasions: ["Birthday", "Just Because"],
    relationship: ["friend", "family"],
    personality: ["artistic", "watercolor", "painter"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["brush", "watercolor", "painting"]
  },
  {
    name: "Digital Drawing Tablet",
    description: "Graphics tablet for digital art creation",
    category: "Art",
    priceMin: 3000,
    priceMax: 8000,
    interests: ["Art", "Technology"],
    occasions: ["Birthday", "Graduation"],
    relationship: ["friend", "family"],
    personality: ["artistic", "digital", "tech-savvy"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["digital", "tablet", "drawing"]
  },

  // Premium/Luxury Items - Budget: Premium
  {
    name: "Espresso Coffee Machine",
    description: "Professional-grade espresso maker for home",
    category: "Cooking",
    priceMin: 15000,
    priceMax: 30000,
    interests: ["Cooking", "Food"],
    occasions: ["Birthday", "Anniversary"],
    relationship: ["partner", "family"],
    personality: ["coffee-lover", "sophisticated", "quality-focused"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["coffee", "espresso", "premium"]
  },
  {
    name: "Designer Handbag Leather",
    description: "Genuine leather designer handbag",
    category: "Fashion",
    priceMin: 8000,
    priceMax: 20000,
    interests: ["Fashion"],
    occasions: ["Birthday", "Anniversary"],
    relationship: ["partner", "family"],
    personality: ["sophisticated", "fashion-forward", "elegant"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["handbag", "designer", "luxury"]
  },
  {
    name: "Home Theater Sound System",
    description: "Premium surround sound system for home entertainment",
    category: "Technology",
    priceMin: 20000,
    priceMax: 50000,
    interests: ["Technology", "Movies", "Music"],
    occasions: ["Anniversary"],
    relationship: ["partner", "family"],
    personality: ["tech-savvy", "entertainment-lover", "quality-focused"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["audio", "home-theater", "premium"]
  },

  // Additional Travel Products
  {
    name: "Luggage Scale Digital",
    description: "Portable digital luggage scale",
    category: "Travel",
    priceMin: 300,
    priceMax: 800,
    interests: ["Travel"],
    occasions: ["Birthday", "Just Because"],
    relationship: ["friend", "family"],
    personality: ["practical", "traveler", "organized"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["luggage", "scale", "travel"]
  },
  {
    name: "Neck Pillow Travel Memory Foam",
    description: "Comfortable memory foam travel neck pillow",
    category: "Travel",
    priceMin: 400,
    priceMax: 1000,
    interests: ["Travel"],
    occasions: ["Birthday", "Just Because"],
    relationship: ["friend", "family"],
    personality: ["comfort-focused", "traveler"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["neck-pillow", "comfort", "travel"]
  },
  {
    name: "Packing Cubes Set",
    description: "Organizational packing cubes for luggage",
    category: "Travel",
    priceMin: 500,
    priceMax: 1200,
    interests: ["Travel"],
    occasions: ["Birthday", "Just Because"],
    relationship: ["friend", "family"],
    personality: ["organized", "traveler", "neat"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["packing", "organizer", "travel"]
  },
  {
    name: "Travel Size Toiletry Kit",
    description: "TSA-approved travel toiletry bottles set",
    category: "Travel",
    priceMin: 300,
    priceMax: 700,
    interests: ["Travel"],
    occasions: ["Birthday", "Just Because"],
    relationship: ["friend", "family"],
    personality: ["practical", "traveler", "organized"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["toiletry", "travel-size", "tsa"]
  },
  {
    name: "Passport Holder Leather",
    description: "Premium leather passport and card holder",
    category: "Travel",
    priceMin: 500,
    priceMax: 1500,
    interests: ["Travel", "Fashion"],
    occasions: ["Birthday", "Graduation"],
    relationship: ["friend", "family", "partner"],
    personality: ["traveler", "organized", "stylish"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["passport", "holder", "leather"]
  },
  {
    name: "Travel Blanket Compact",
    description: "Compact travel blanket with carry pouch",
    category: "Travel",
    priceMin: 600,
    priceMax: 1500,
    interests: ["Travel"],
    occasions: ["Birthday", "Just Because"],
    relationship: ["friend", "family"],
    personality: ["comfort-focused", "traveler"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["blanket", "compact", "travel"]
  },
  {
    name: "Luggage Tag Personalized",
    description: "Customizable leather luggage tag",
    category: "Travel",
    priceMin: 200,
    priceMax: 600,
    interests: ["Travel"],
    occasions: ["Birthday", "Just Because"],
    relationship: ["friend", "family"],
    personality: ["traveler", "personalized", "organized"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["luggage-tag", "personalized", "travel"]
  },
  {
    name: "Travel Security Lock TSA",
    description: "TSA-approved combination lock for luggage",
    category: "Travel",
    priceMin: 200,
    priceMax: 500,
    interests: ["Travel"],
    occasions: ["Birthday", "Just Because"],
    relationship: ["friend", "family"],
    personality: ["security-conscious", "traveler", "practical"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["lock", "security", "tsa"]
  },
  {
    name: "Compression Socks Travel",
    description: "Compression socks for long flights",
    category: "Travel",
    priceMin: 400,
    priceMax: 1000,
    interests: ["Travel", "Fitness"],
    occasions: ["Birthday", "Just Because"],
    relationship: ["friend", "family"],
    personality: ["health-conscious", "traveler"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["compression", "socks", "health"]
  },
  {
    name: "Travel Camera Action Cam",
    description: "Waterproof action camera for adventure travel",
    category: "Travel",
    priceMin: 8000,
    priceMax: 15000,
    interests: ["Travel", "Photography", "Sports"],
    occasions: ["Birthday", "Graduation"],
    relationship: ["friend", "family", "partner"],
    personality: ["adventurous", "photographer", "active"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["camera", "action", "waterproof"]
  },

  // Additional Cooking Products
  {
    name: "Air Fryer Multi-Function",
    description: "Digital air fryer with multiple cooking modes",
    category: "Cooking",
    priceMin: 3000,
    priceMax: 6000,
    interests: ["Cooking", "Food"],
    occasions: ["Birthday", "Anniversary"],
    relationship: ["family", "partner"],
    personality: ["health-conscious", "culinary", "modern"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["air-fryer", "appliance", "healthy"]
  },
  {
    name: "Cutting Board Bamboo Set",
    description: "Eco-friendly bamboo cutting boards in multiple sizes",
    category: "Cooking",
    priceMin: 600,
    priceMax: 1500,
    interests: ["Cooking"],
    occasions: ["Birthday", "Just Because"],
    relationship: ["friend", "family"],
    personality: ["eco-conscious", "culinary", "practical"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["cutting-board", "bamboo", "eco-friendly"]
  },
  {
    name: "Mixing Bowl Stainless Steel Set",
    description: "Nesting stainless steel mixing bowls",
    category: "Cooking",
    priceMin: 800,
    priceMax: 1800,
    interests: ["Cooking"],
    occasions: ["Birthday", "Just Because"],
    relationship: ["friend", "family"],
    personality: ["culinary", "organized", "practical"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["mixing-bowl", "steel", "kitchen"]
  },
  {
    name: "Kitchen Knife Sharpener Electric",
    description: "Electric knife sharpener for all blade types",
    category: "Cooking",
    priceMin: 1500,
    priceMax: 3000,
    interests: ["Cooking"],
    occasions: ["Birthday", "Just Because"],
    relationship: ["family", "friend"],
    personality: ["culinary", "maintenance", "practical"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["sharpener", "knife", "electric"]
  },
  {
    name: "Pasta Maker Machine",
    description: "Manual pasta maker with multiple cutter attachments",
    category: "Cooking",
    priceMin: 1500,
    priceMax: 3500,
    interests: ["Cooking", "Food"],
    occasions: ["Birthday", "Anniversary"],
    relationship: ["family", "partner"],
    personality: ["culinary", "traditional", "artisan"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["pasta", "maker", "italian"]
  },
  {
    name: "Kitchen Scale Digital",
    description: "Precision digital kitchen scale for baking",
    category: "Cooking",
    priceMin: 500,
    priceMax: 1200,
    interests: ["Cooking"],
    occasions: ["Birthday", "Just Because"],
    relationship: ["friend", "family"],
    personality: ["precise", "baker", "culinary"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["scale", "digital", "baking"]
  },
  {
    name: "Herb Garden Indoor Kit",
    description: "Indoor herb growing kit for kitchen",
    category: "Cooking",
    priceMin: 800,
    priceMax: 2000,
    interests: ["Cooking", "Nature"],
    occasions: ["Birthday", "Just Because"],
    relationship: ["friend", "family"],
    personality: ["culinary", "fresh", "nature-lover"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["herbs", "garden", "indoor"]
  },
  {
    name: "Measuring Cups and Spoons Set",
    description: "Stainless steel measuring cups and spoons",
    category: "Cooking",
    priceMin: 300,
    priceMax: 800,
    interests: ["Cooking"],
    occasions: ["Birthday", "Just Because"],
    relationship: ["friend", "family"],
    personality: ["precise", "baker", "culinary"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["measuring", "baking", "tools"]
  },
  {
    name: "Cast Iron Skillet Pan",
    description: "Pre-seasoned cast iron cooking pan",
    category: "Cooking",
    priceMin: 1000,
    priceMax: 2500,
    interests: ["Cooking"],
    occasions: ["Birthday", "Anniversary"],
    relationship: ["family", "partner"],
    personality: ["traditional", "culinary", "quality-focused"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["cast-iron", "skillet", "cookware"]
  },
  {
    name: "Blender High-Speed",
    description: "Professional high-speed blender for smoothies",
    category: "Cooking",
    priceMin: 3000,
    priceMax: 8000,
    interests: ["Cooking", "Food", "Fitness"],
    occasions: ["Birthday", "Anniversary"],
    relationship: ["family", "partner"],
    personality: ["health-conscious", "culinary", "modern"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["blender", "smoothie", "appliance"]
  },

  // Additional Gaming Products
  {
    name: "Gaming Chair Ergonomic",
    description: "Professional gaming chair with lumbar support",
    category: "Gaming",
    priceMin: 8000,
    priceMax: 15000,
    interests: ["Gaming"],
    occasions: ["Birthday", "Graduation"],
    relationship: ["friend", "family"],
    personality: ["gamer", "comfort-focused", "serious"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["chair", "gaming", "ergonomic"]
  },
  {
    name: "Mechanical Keyboard Gaming RGB",
    description: "RGB mechanical gaming keyboard with custom switches",
    category: "Gaming",
    priceMin: 3000,
    priceMax: 8000,
    interests: ["Gaming", "Technology"],
    occasions: ["Birthday", "Graduation"],
    relationship: ["friend", "family"],
    personality: ["gamer", "tech-savvy", "performance"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["keyboard", "mechanical", "gaming"]
  },
  {
    name: "VR Headset Gaming",
    description: "Virtual reality headset for immersive gaming",
    category: "Gaming",
    priceMin: 15000,
    priceMax: 35000,
    interests: ["Gaming", "Technology"],
    occasions: ["Birthday", "Graduation", "Anniversary"],
    relationship: ["family", "partner"],
    personality: ["gamer", "tech-savvy", "innovative"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["vr", "headset", "virtual-reality"]
  },
  {
    name: "Gaming Monitor 144Hz",
    description: "High refresh rate gaming monitor 27 inch",
    category: "Gaming",
    priceMin: 12000,
    priceMax: 25000,
    interests: ["Gaming", "Technology"],
    occasions: ["Birthday", "Graduation"],
    relationship: ["friend", "family"],
    personality: ["gamer", "competitive", "quality-focused"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["monitor", "144hz", "gaming"]
  },
  {
    name: "Controller Charging Dock",
    description: "Dual controller charging station",
    category: "Gaming",
    priceMin: 800,
    priceMax: 1800,
    interests: ["Gaming", "Technology"],
    occasions: ["Birthday", "Just Because"],
    relationship: ["friend", "family"],
    personality: ["gamer", "organized", "practical"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["charger", "controller", "dock"]
  },
  {
    name: "Gaming Mousepad XXL",
    description: "Extended gaming mousepad with RGB lighting",
    category: "Gaming",
    priceMin: 1000,
    priceMax: 2500,
    interests: ["Gaming", "Technology"],
    occasions: ["Birthday", "Just Because"],
    relationship: ["friend", "family"],
    personality: ["gamer", "setup-focused", "rgb"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["mousepad", "rgb", "gaming"]
  },
  {
    name: "Game Capture Card",
    description: "HD game capture card for streaming",
    category: "Gaming",
    priceMin: 4000,
    priceMax: 10000,
    interests: ["Gaming", "Technology"],
    occasions: ["Birthday", "Graduation"],
    relationship: ["friend", "family"],
    personality: ["gamer", "streamer", "content-creator"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["capture", "streaming", "recording"]
  },
  {
    name: "Racing Wheel and Pedals",
    description: "Sim racing wheel with force feedback",
    category: "Gaming",
    priceMin: 10000,
    priceMax: 25000,
    interests: ["Gaming", "Sports"],
    occasions: ["Birthday"],
    relationship: ["friend", "family"],
    personality: ["gamer", "racing-enthusiast", "immersive"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["racing", "wheel", "simulator"]
  },
  {
    name: "Gaming Desk L-Shaped",
    description: "Spacious L-shaped gaming desk with cable management",
    category: "Gaming",
    priceMin: 8000,
    priceMax: 15000,
    interests: ["Gaming"],
    occasions: ["Birthday", "Graduation"],
    relationship: ["family", "friend"],
    personality: ["gamer", "organized", "space-conscious"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["desk", "gaming", "furniture"]
  },
  {
    name: "Retro Gaming Console",
    description: "Classic gaming console with pre-loaded games",
    category: "Gaming",
    priceMin: 3000,
    priceMax: 6000,
    interests: ["Gaming"],
    occasions: ["Birthday", "Anniversary"],
    relationship: ["friend", "family", "partner"],
    personality: ["nostalgic", "gamer", "retro"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["retro", "console", "classic"]
  },

  // Additional Fashion Products
  {
    name: "Belt Leather Reversible",
    description: "Reversible leather belt black and brown",
    category: "Fashion",
    priceMin: 800,
    priceMax: 2000,
    interests: ["Fashion"],
    occasions: ["Birthday", "Anniversary"],
    relationship: ["partner", "family", "friend"],
    personality: ["professional", "practical", "stylish"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["belt", "leather", "accessory"]
  },
  {
    name: "Tie Set Formal",
    description: "Set of silk ties with matching pocket squares",
    category: "Fashion",
    priceMin: 1200,
    priceMax: 3000,
    interests: ["Fashion"],
    occasions: ["Birthday", "Graduation"],
    relationship: ["partner", "family", "friend", "colleague"],
    personality: ["professional", "formal", "elegant"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["tie", "formal", "accessory"]
  },
  {
    name: "Cufflinks Designer Set",
    description: "Premium designer cufflinks in gift box",
    category: "Fashion",
    priceMin: 1500,
    priceMax: 4000,
    interests: ["Fashion"],
    occasions: ["Birthday", "Anniversary", "Graduation"],
    relationship: ["partner", "family", "colleague"],
    personality: ["professional", "sophisticated", "detailed"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["cufflinks", "formal", "accessory"]
  },
  {
    name: "Hat Fedora Classic",
    description: "Classic fedora hat in wool felt",
    category: "Fashion",
    priceMin: 1200,
    priceMax: 3000,
    interests: ["Fashion"],
    occasions: ["Birthday", "Just Because"],
    relationship: ["friend", "family", "partner"],
    personality: ["stylish", "vintage", "distinctive"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["hat", "fedora", "accessory"]
  },
  {
    name: "Jewelry Box Organizer",
    description: "Multi-tier jewelry organizer with mirror",
    category: "Fashion",
    priceMin: 1000,
    priceMax: 2500,
    interests: ["Fashion"],
    occasions: ["Birthday", "Anniversary"],
    relationship: ["partner", "family", "friend"],
    personality: ["organized", "fashion-lover", "neat"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["jewelry", "organizer", "storage"]
  },
  {
    name: "Perfume Gift Set Luxury",
    description: "Premium fragrance collection gift set",
    category: "Fashion",
    priceMin: 3000,
    priceMax: 8000,
    interests: ["Fashion"],
    occasions: ["Birthday", "Anniversary"],
    relationship: ["partner", "family"],
    personality: ["sophisticated", "elegant", "luxury-oriented"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["perfume", "fragrance", "luxury"]
  },
  {
    name: "Backpack Laptop Stylish",
    description: "Fashionable laptop backpack with USB port",
    category: "Fashion",
    priceMin: 1500,
    priceMax: 3500,
    interests: ["Fashion", "Technology"],
    occasions: ["Birthday", "Graduation"],
    relationship: ["friend", "family", "colleague"],
    personality: ["modern", "practical", "stylish"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["backpack", "laptop", "fashion"]
  },
  {
    name: "Gloves Leather Winter",
    description: "Genuine leather gloves with wool lining",
    category: "Fashion",
    priceMin: 1000,
    priceMax: 2500,
    interests: ["Fashion"],
    occasions: ["Birthday", "Holiday"],
    relationship: ["partner", "family", "friend"],
    personality: ["practical", "elegant", "warm"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["gloves", "leather", "winter"]
  },
  {
    name: "Jewelry Earrings Sterling Silver",
    description: "Sterling silver earrings with gemstone",
    category: "Fashion",
    priceMin: 2000,
    priceMax: 5000,
    interests: ["Fashion"],
    occasions: ["Birthday", "Anniversary"],
    relationship: ["partner", "family"],
    personality: ["elegant", "jewelry-lover", "sophisticated"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["earrings", "jewelry", "silver"]
  },
  {
    name: "Bracelet Charm Personalized",
    description: "Customizable charm bracelet",
    category: "Fashion",
    priceMin: 1500,
    priceMax: 4000,
    interests: ["Fashion"],
    occasions: ["Birthday", "Anniversary"],
    relationship: ["partner", "family", "friend"],
    personality: ["sentimental", "personalized", "jewelry-lover"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["bracelet", "charm", "personalized"]
  },

  // Additional Photography Products
  {
    name: "Camera Bag Professional",
    description: "Waterproof camera bag with padded compartments",
    category: "Photography",
    priceMin: 2000,
    priceMax: 5000,
    interests: ["Photography"],
    occasions: ["Birthday", "Graduation"],
    relationship: ["friend", "family"],
    personality: ["photographer", "organized", "protective"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["bag", "camera", "storage"]
  },
  {
    name: "Lens Cleaning Kit Professional",
    description: "Complete lens cleaning and maintenance kit",
    category: "Photography",
    priceMin: 500,
    priceMax: 1200,
    interests: ["Photography"],
    occasions: ["Birthday", "Just Because"],
    relationship: ["friend", "family"],
    personality: ["photographer", "meticulous", "maintenance"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["cleaning", "lens", "maintenance"]
  },
  {
    name: "Camera Flash External",
    description: "TTL external flash for DSLR cameras",
    category: "Photography",
    priceMin: 4000,
    priceMax: 10000,
    interests: ["Photography"],
    occasions: ["Birthday", "Graduation"],
    relationship: ["friend", "family"],
    personality: ["photographer", "professional", "lighting"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["flash", "lighting", "camera"]
  },
  {
    name: "Photography Backdrop Kit",
    description: "Portable backdrop stand with multiple backgrounds",
    category: "Photography",
    priceMin: 3000,
    priceMax: 7000,
    interests: ["Photography"],
    occasions: ["Birthday", "Graduation"],
    relationship: ["friend", "family"],
    personality: ["photographer", "studio", "creative"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["backdrop", "studio", "photography"]
  },
  {
    name: "Camera Remote Shutter",
    description: "Wireless remote shutter release",
    category: "Photography",
    priceMin: 500,
    priceMax: 1500,
    interests: ["Photography"],
    occasions: ["Birthday", "Just Because"],
    relationship: ["friend", "family"],
    personality: ["photographer", "practical", "technical"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["remote", "shutter", "wireless"]
  },
  {
    name: "SD Card High Speed 128GB",
    description: "Fast SD card for high-resolution photography",
    category: "Photography",
    priceMin: 1500,
    priceMax: 3000,
    interests: ["Photography", "Technology"],
    occasions: ["Birthday", "Just Because"],
    relationship: ["friend", "family"],
    personality: ["photographer", "professional", "tech-savvy"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["sd-card", "storage", "memory"]
  },
  {
    name: "Photo Printer Portable",
    description: "Wireless portable photo printer",
    category: "Photography",
    priceMin: 5000,
    priceMax: 10000,
    interests: ["Photography", "Technology"],
    occasions: ["Birthday", "Anniversary"],
    relationship: ["friend", "family", "partner"],
    personality: ["photographer", "nostalgic", "creative"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["printer", "portable", "photo"]
  },
  {
    name: "Lightroom Presets Pack",
    description: "Professional Lightroom presets collection",
    category: "Photography",
    priceMin: 1000,
    priceMax: 2500,
    interests: ["Photography", "Technology"],
    occasions: ["Birthday", "Just Because"],
    relationship: ["friend", "family"],
    personality: ["photographer", "editor", "creative"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["presets", "lightroom", "editing"]
  },
  {
    name: "Camera Lens Filter Set",
    description: "ND and polarizing filter set for lenses",
    category: "Photography",
    priceMin: 2000,
    priceMax: 5000,
    interests: ["Photography"],
    occasions: ["Birthday", "Graduation"],
    relationship: ["friend", "family"],
    personality: ["photographer", "technical", "quality-focused"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["filter", "lens", "photography"]
  },
  {
    name: "Ring Light for Photography",
    description: "LED ring light with adjustable brightness",
    category: "Photography",
    priceMin: 2000,
    priceMax: 5000,
    interests: ["Photography"],
    occasions: ["Birthday", "Just Because"],
    relationship: ["friend", "family"],
    personality: ["photographer", "content-creator", "lighting"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["ring-light", "led", "lighting"]
  },

  // Premium Technology Products ₹50k+
  {
    name: "MacBook Pro Laptop Premium",
    description: "High-performance MacBook Pro for professionals",
    category: "Technology",
    priceMin: 80000,
    priceMax: 150000,
    interests: ["Technology"],
    occasions: ["Graduation", "Anniversary"],
    relationship: ["family", "partner"],
    personality: ["professional", "tech-savvy", "creative"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["laptop", "macbook", "premium"]
  },
  {
    name: "iPhone Pro Max Latest Model",
    description: "Latest iPhone Pro Max with maximum storage",
    category: "Technology",
    priceMin: 120000,
    priceMax: 160000,
    interests: ["Technology"],
    occasions: ["Birthday", "Graduation", "Anniversary"],
    relationship: ["family", "partner"],
    personality: ["tech-savvy", "modern", "premium"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["smartphone", "iphone", "premium"]
  },
  {
    name: "Gaming PC Custom Build",
    description: "High-end gaming PC with RTX graphics card",
    category: "Gaming",
    priceMin: 100000,
    priceMax: 200000,
    interests: ["Gaming", "Technology"],
    occasions: ["Birthday", "Graduation"],
    relationship: ["family"],
    personality: ["gamer", "tech-enthusiast", "performance"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["gaming-pc", "custom", "premium"]
  },
  {
    name: "Professional DSLR Camera Full Frame",
    description: "Full-frame professional DSLR camera body",
    category: "Photography",
    priceMin: 150000,
    priceMax: 250000,
    interests: ["Photography"],
    occasions: ["Graduation"],
    relationship: ["family"],
    personality: ["professional", "photographer", "serious"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["dslr", "camera", "professional"]
  },
  {
    name: "Electric Scooter Premium",
    description: "High-performance electric scooter with long range",
    category: "Travel",
    priceMin: 50000,
    priceMax: 100000,
    interests: ["Technology", "Travel"],
    occasions: ["Birthday", "Graduation"],
    relationship: ["family", "partner"],
    personality: ["eco-conscious", "modern", "commuter"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["scooter", "electric", "transport"]
  },
  {
    name: "Diamond Jewelry Ring",
    description: "Diamond engagement or anniversary ring",
    category: "Fashion",
    priceMin: 100000,
    priceMax: 500000,
    interests: ["Fashion"],
    occasions: ["Anniversary"],
    relationship: ["partner"],
    personality: ["romantic", "luxury-oriented", "traditional"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["jewelry", "diamond", "luxury"]
  },
  {
    name: "Grand Piano Digital Professional",
    description: "Professional digital grand piano with weighted keys",
    category: "Music",
    priceMin: 80000,
    priceMax: 200000,
    interests: ["Music"],
    occasions: ["Birthday", "Graduation"],
    relationship: ["family"],
    personality: ["musical", "serious", "pianist"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["piano", "digital", "professional"]
  },
  {
    name: "Home Gym Equipment Complete Set",
    description: "Complete home gym with squat rack, bench, weights",
    category: "Fitness",
    priceMin: 50000,
    priceMax: 150000,
    interests: ["Fitness", "Sports"],
    occasions: ["Birthday"],
    relationship: ["family", "partner"],
    personality: ["fitness-enthusiast", "dedicated", "serious"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["home-gym", "complete", "premium"]
  },

  // Additional Standard Range Products
  {
    name: "Electric Toothbrush Premium",
    description: "Smart electric toothbrush with app connectivity",
    category: "Fitness",
    priceMin: 3000,
    priceMax: 8000,
    interests: ["Fitness"],
    occasions: ["Birthday", "Just Because"],
    relationship: ["friend", "family"],
    personality: ["health-conscious", "tech-savvy", "hygiene-focused"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["toothbrush", "electric", "dental"]
  },
  {
    name: "Perfume Making DIY Kit",
    description: "Complete kit to create custom perfumes at home",
    category: "DIY/Crafts",
    priceMin: 0,
    priceMax: 0,
    interests: ["DIY/Crafts", "Fashion"],
    occasions: ["Birthday", "Just Because"],
    relationship: ["friend", "family"],
    personality: ["creative", "unique", "artisan"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["diy", "perfume", "fragrance"]
  },
  {
    name: "Ceramic Plant Pots Set Decorative",
    description: "Hand-painted ceramic planters set of 3",
    category: "Nature",
    priceMin: 800,
    priceMax: 2000,
    interests: ["Nature", "Art"],
    occasions: ["Birthday", "Just Because"],
    relationship: ["friend", "family"],
    personality: ["nature-lover", "decorative", "aesthetic"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["planters", "ceramic", "decorative"]
  },
  {
    name: "Comic Book Collectible Edition",
    description: "Rare collectible comic book in protective case",
    category: "Books",
    priceMin: 2000,
    priceMax: 10000,
    interests: ["Books", "Art"],
    occasions: ["Birthday"],
    relationship: ["friend", "family"],
    personality: ["collector", "nostalgic", "comic-fan"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["comics", "collectible", "rare"]
  },
  {
    name: "Telescope Astronomical",
    description: "Astronomical telescope for stargazing",
    category: "Nature",
    priceMin: 8000,
    priceMax: 20000,
    interests: ["Nature", "Technology"],
    occasions: ["Birthday", "Graduation"],
    relationship: ["family", "friend"],
    personality: ["curious", "astronomer", "explorer"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["telescope", "astronomy", "stargazing"]
  },
  {
    name: "Sushi Making Kit Professional",
    description: "Complete sushi preparation kit with tools and ingredients",
    category: "Cooking",
    priceMin: 1500,
    priceMax: 3500,
    interests: ["Cooking", "Food"],
    occasions: ["Birthday", "Just Because"],
    relationship: ["friend", "family"],
    personality: ["culinary", "japanese-food", "adventurous"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["sushi", "japanese", "cooking"]
  },
  {
    name: "Drone with Camera 4K",
    description: "Professional drone with 4K camera for aerial photography",
    category: "Photography",
    priceMin: 25000,
    priceMax: 60000,
    interests: ["Photography", "Technology"],
    occasions: ["Birthday", "Graduation"],
    relationship: ["friend", "family"],
    personality: ["tech-savvy", "photographer", "adventurous"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["drone", "camera", "aerial"]
  },
  {
    name: "Leather Journal Handmade",
    description: "Artisan handmade leather-bound journal",
    category: "Books",
    priceMin: 1000,
    priceMax: 3000,
    interests: ["Books", "Art"],
    occasions: ["Birthday", "Graduation", "Just Because"],
    relationship: ["friend", "family", "partner"],
    personality: ["thoughtful", "writer", "artistic"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["journal", "leather", "handmade"]
  },
  {
    name: "Chess Set Luxury Wooden",
    description: "Handcrafted wooden chess set with storage",
    category: "Gaming",
    priceMin: 3000,
    priceMax: 8000,
    interests: ["Gaming"],
    occasions: ["Birthday", "Anniversary"],
    relationship: ["friend", "family", "partner"],
    personality: ["strategic", "classic", "intellectual"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["chess", "wooden", "luxury"]
  },
  {
    name: "Hiking Boots Professional",
    description: "Waterproof hiking boots with ankle support",
    category: "Sports",
    priceMin: 4000,
    priceMax: 10000,
    interests: ["Sports", "Nature", "Travel"],
    occasions: ["Birthday", "Graduation"],
    relationship: ["friend", "family"],
    personality: ["outdoorsy", "adventurous", "active"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["hiking", "boots", "outdoor"]
  },
  {
    name: "Cocktail Making Set Professional",
    description: "Professional bartender cocktail shaker set",
    category: "Cooking",
    priceMin: 1500,
    priceMax: 4000,
    interests: ["Cooking", "Food"],
    occasions: ["Birthday", "Anniversary"],
    relationship: ["friend", "partner"],
    personality: ["social", "mixologist", "entertaining"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["cocktail", "bartender", "mixology"]
  },
  {
    name: "Wall Art Canvas Print Custom",
    description: "Custom canvas print of personal photo or artwork",
    category: "Art",
    priceMin: 1500,
    priceMax: 5000,
    interests: ["Art", "Photography"],
    occasions: ["Birthday", "Anniversary"],
    relationship: ["partner", "family", "friend"],
    personality: ["sentimental", "artistic", "personalized"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["wall-art", "canvas", "custom"]
  },
  {
    name: "Bluetooth Karaoke Microphone",
    description: "Wireless karaoke microphone with speaker",
    category: "Music",
    priceMin: 1000,
    priceMax: 3000,
    interests: ["Music"],
    occasions: ["Birthday", "Just Because"],
    relationship: ["friend", "family"],
    personality: ["fun", "singer", "entertaining"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["karaoke", "microphone", "party"]
  },
  {
    name: "Bath Bombs Gift Set Luxury",
    description: "Luxury aromatherapy bath bomb collection",
    category: "Fashion",
    priceMin: 800,
    priceMax: 2000,
    interests: ["Fashion"],
    occasions: ["Birthday", "Just Because"],
    relationship: ["friend", "family", "partner"],
    personality: ["relaxed", "self-care", "wellness"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["bath", "aromatherapy", "spa"]
  },
  {
    name: "Pocket Watch Vintage Style",
    description: "Vintage-inspired mechanical pocket watch",
    category: "Fashion",
    priceMin: 2000,
    priceMax: 6000,
    interests: ["Fashion"],
    occasions: ["Birthday", "Anniversary", "Graduation"],
    relationship: ["partner", "family", "friend"],
    personality: ["vintage", "sophisticated", "unique"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["pocket-watch", "vintage", "timepiece"]
  },
  {
    name: "Embroidery Kit Beginner",
    description: "Complete embroidery starter kit with patterns",
    category: "DIY/Crafts",
    priceMin: 400,
    priceMax: 1000,
    interests: ["DIY/Crafts", "Art"],
    occasions: ["Birthday", "Just Because"],
    relationship: ["friend", "family"],
    personality: ["creative", "patient", "traditional"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["embroidery", "crafts", "starter"]
  },
  {
    name: "Succulent Plant Collection",
    description: "Collection of 5 different succulent plants",
    category: "Nature",
    priceMin: 500,
    priceMax: 1500,
    interests: ["Nature"],
    occasions: ["Birthday", "Just Because"],
    relationship: ["friend", "family", "colleague"],
    personality: ["nature-lover", "low-maintenance", "green-thumb"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["succulents", "plants", "collection"]
  },
  {
    name: "Sous Vide Cooking Machine",
    description: "Precision sous vide cooker for gourmet meals",
    category: "Cooking",
    priceMin: 6000,
    priceMax: 15000,
    interests: ["Cooking", "Food"],
    occasions: ["Birthday", "Anniversary"],
    relationship: ["family", "partner"],
    personality: ["culinary", "gourmet", "tech-savvy"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["sous-vide", "precision", "gourmet"]
  },
  {
    name: "Sketchbook Professional Artist",
    description: "Premium heavyweight paper sketchbook",
    category: "Art",
    priceMin: 600,
    priceMax: 1500,
    interests: ["Art"],
    occasions: ["Birthday", "Just Because"],
    relationship: ["friend", "family"],
    personality: ["artistic", "sketcher", "professional"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["sketchbook", "professional", "paper"]
  },
  {
    name: "Camping Tent 4-Person",
    description: "Waterproof camping tent for 4 people",
    category: "Nature",
    priceMin: 5000,
    priceMax: 12000,
    interests: ["Nature", "Travel"],
    occasions: ["Birthday", "Graduation"],
    relationship: ["family", "friend"],
    personality: ["outdoorsy", "adventurous", "camper"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["tent", "camping", "outdoor"]
  },
  {
    name: "Pen Set Luxury Writing",
    description: "Luxury fountain pen and ballpoint pen set",
    category: "Books",
    priceMin: 3000,
    priceMax: 10000,
    interests: ["Books"],
    occasions: ["Birthday", "Graduation", "Anniversary"],
    relationship: ["colleague", "partner", "family"],
    personality: ["professional", "writer", "sophisticated"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["pen", "writing", "luxury"]
  },
  {
    name: "Spa Gift Certificate Luxury",
    description: "Premium spa treatment package voucher",
    category: "Fashion",
    priceMin: 5000,
    priceMax: 15000,
    interests: ["Fashion"],
    occasions: ["Birthday", "Anniversary"],
    relationship: ["partner", "family"],
    personality: ["relaxed", "self-care", "wellness"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["spa", "gift-certificate", "wellness"]
  },
  {
    name: "Meditation Cushion Set",
    description: "Zafu and zabuton meditation cushion set",
    category: "Fitness",
    priceMin: 1500,
    priceMax: 4000,
    interests: ["Fitness"],
    occasions: ["Birthday", "Just Because"],
    relationship: ["friend", "family"],
    personality: ["mindful", "spiritual", "wellness-focused"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["meditation", "cushion", "mindfulness"]
  },
  {
    name: "Bartending Recipe Book",
    description: "Comprehensive cocktail and mixology guide",
    category: "Books",
    priceMin: 600,
    priceMax: 1500,
    interests: ["Books", "Cooking", "Food"],
    occasions: ["Birthday", "Just Because"],
    relationship: ["friend", "partner"],
    personality: ["social", "mixologist", "learner"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["cocktail", "recipe", "bartending"]
  },
  {
    name: "Action Figures Collectible Set",
    description: "Limited edition collectible action figure set",
    category: "Gaming",
    priceMin: 3000,
    priceMax: 12000,
    interests: ["Gaming", "Movies"],
    occasions: ["Birthday"],
    relationship: ["friend", "family"],
    personality: ["collector", "fan", "nostalgic"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["action-figures", "collectible", "toys"]
  },
  {
    name: "Wireless Charger Fast Charging",
    description: "Fast wireless charging pad for multiple devices",
    category: "Technology",
    priceMin: 1500,
    priceMax: 3500,
    interests: ["Technology"],
    occasions: ["Birthday", "Just Because"],
    relationship: ["friend", "family", "colleague"],
    personality: ["tech-savvy", "organized", "modern"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["wireless", "charger", "fast"]
  },
  {
    name: "Gardening Book Encyclopedia",
    description: "Complete encyclopedia of gardening and plants",
    category: "Books",
    priceMin: 1000,
    priceMax: 2500,
    interests: ["Books", "Nature"],
    occasions: ["Birthday", "Just Because"],
    relationship: ["friend", "family"],
    personality: ["nature-lover", "gardener", "learner"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["gardening", "encyclopedia", "plants"]
  },
  {
    name: "Projector Home Cinema",
    description: "Full HD home cinema projector",
    category: "Movies",
    priceMin: 15000,
    priceMax: 40000,
    interests: ["Movies", "Technology"],
    occasions: ["Birthday", "Anniversary"],
    relationship: ["family", "partner"],
    personality: ["cinephile", "tech-savvy", "entertainment-lover"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["projector", "home-cinema", "entertainment"]
  },
  {
    name: "Rock Climbing Gear Set",
    description: "Complete rock climbing gear with harness and rope",
    category: "Sports",
    priceMin: 8000,
    priceMax: 20000,
    interests: ["Sports", "Nature"],
    occasions: ["Birthday", "Graduation"],
    relationship: ["friend", "family"],
    personality: ["adventurous", "extreme", "climber"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["climbing", "gear", "extreme"]
  },
  {
    name: "Leather Messenger Bag",
    description: "Vintage leather messenger bag for laptop",
    category: "Fashion",
    priceMin: 3000,
    priceMax: 8000,
    interests: ["Fashion", "Technology"],
    occasions: ["Birthday", "Graduation"],
    relationship: ["friend", "family", "colleague"],
    personality: ["professional", "vintage", "organized"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["messenger-bag", "leather", "laptop"]
  },
  {
    name: "Yoga Instructor Course Online",
    description: "200-hour yoga teacher training certification online",
    category: "Fitness",
    priceMin: 15000,
    priceMax: 40000,
    interests: ["Fitness"],
    occasions: ["Birthday", "Graduation"],
    relationship: ["friend", "family"],
    personality: ["yogis", "instructor", "dedicated"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["yoga", "certification", "training"]
  },
  {
    name: "Pasta Sauce Making Kit Gourmet",
    description: "Gourmet Italian pasta sauce making kit",
    category: "Cooking",
    priceMin: 800,
    priceMax: 2000,
    interests: ["Cooking", "Food"],
    occasions: ["Birthday", "Just Because"],
    relationship: ["friend", "family"],
    personality: ["culinary", "italian-food", "artisan"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["pasta", "sauce", "italian"]
  },
  {
    name: "Personalized Name Necklace",
    description: "Custom name or initial necklace in gold/silver",
    category: "Fashion",
    priceMin: 2000,
    priceMax: 8000,
    interests: ["Fashion"],
    occasions: ["Birthday", "Anniversary"],
    relationship: ["partner", "family", "friend"],
    personality: ["personalized", "jewelry-lover", "sentimental"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["necklace", "personalized", "jewelry"]
  },
  {
    name: "Bird Feeder Decorative Garden",
    description: "Decorative bird feeder for garden",
    category: "Nature",
    priceMin: 600,
    priceMax: 1800,
    interests: ["Nature"],
    occasions: ["Birthday", "Just Because"],
    relationship: ["friend", "family"],
    personality: ["nature-lover", "bird-watcher", "caring"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["bird-feeder", "garden", "wildlife"]
  },
  {
    name: "Origami Paper Set Premium",
    description: "Premium origami paper with instruction book",
    category: "DIY/Crafts",
    priceMin: 300,
    priceMax: 800,
    interests: ["DIY/Crafts", "Art"],
    occasions: ["Birthday", "Just Because"],
    relationship: ["friend", "family"],
    personality: ["patient", "precise", "creative"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["origami", "paper", "crafts"]
  },
  {
    name: "Electric Bicycle Premium",
    description: "Electric bicycle with long-range battery",
    category: "Sports",
    priceMin: 40000,
    priceMax: 100000,
    interests: ["Sports", "Technology", "Travel"],
    occasions: ["Birthday", "Graduation"],
    relationship: ["family", "partner"],
    personality: ["eco-conscious", "active", "commuter"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["ebike", "bicycle", "electric"]
  },
  {
    name: "Smart Doorbell Camera",
    description: "Video doorbell with motion detection and app control",
    category: "Technology",
    priceMin: 8000,
    priceMax: 18000,
    interests: ["Technology"],
    occasions: ["Birthday", "Anniversary"],
    relationship: ["family", "partner"],
    personality: ["tech-savvy", "security-conscious", "smart-home"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["doorbell", "camera", "smart-home"]
  },
  
  // Diwali Special Gifts - Traditional & Modern
  {
    name: "Traditional Diya Set (Pack of 12)",
    description: "Handcrafted clay diyas with decorative patterns, perfect for Diwali celebrations",
    category: "Home Decor",
    priceMin: 250,
    priceMax: 600,
    interests: ["Home Decor", "Art"],
    occasions: ["Diwali", "Festival", "Just Because"],
    relationship: ["friend", "family", "colleague"],
    personality: ["traditional", "festive", "cultural"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["diwali", "diya", "traditional", "festival"]
  },
  {
    name: "Decorative Rangoli Stencil Set",
    description: "Reusable rangoli stencils with vibrant colors for beautiful floor art",
    category: "Home Decor",
    priceMin: 300,
    priceMax: 800,
    interests: ["Art", "DIY/Crafts", "Home Decor"],
    occasions: ["Diwali", "Festival"],
    relationship: ["friend", "family"],
    personality: ["creative", "traditional", "artistic"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["diwali", "rangoli", "decoration", "festival"]
  },
  {
    name: "Silver Plated Lakshmi Ganesh Idol",
    description: "Elegant silver-plated idol set for Diwali puja and home decoration",
    category: "Home Decor",
    priceMin: 1500,
    priceMax: 4000,
    interests: ["Home Decor"],
    occasions: ["Diwali", "Festival", "Anniversary"],
    relationship: ["family", "partner", "friend"],
    personality: ["traditional", "spiritual", "cultured"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["diwali", "idol", "silver", "puja", "festival"]
  },
  {
    name: "LED String Lights Decorative (10m)",
    description: "Colorful LED fairy lights for Diwali decoration, energy-efficient",
    category: "Home Decor",
    priceMin: 400,
    priceMax: 1200,
    interests: ["Home Decor"],
    occasions: ["Diwali", "Festival", "Birthday"],
    relationship: ["friend", "family", "colleague"],
    personality: ["festive", "modern", "cheerful"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["diwali", "lights", "led", "decoration", "festival"]
  },
  {
    name: "Premium Dry Fruits Gift Box",
    description: "Assorted premium dry fruits and nuts in elegant packaging, perfect for Diwali gifting",
    category: "Food",
    priceMin: 800,
    priceMax: 2500,
    interests: ["Food"],
    occasions: ["Diwali", "Festival", "Anniversary", "Birthday"],
    relationship: ["friend", "family", "colleague", "partner"],
    personality: ["health-conscious", "traditional", "generous"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["diwali", "dry-fruits", "gift-box", "healthy", "festival"]
  },
  {
    name: "Decorative Toran Door Hanging",
    description: "Handcrafted traditional toran with beads and bells for entrance decoration",
    category: "Home Decor",
    priceMin: 350,
    priceMax: 900,
    interests: ["Home Decor", "Art"],
    occasions: ["Diwali", "Festival"],
    relationship: ["friend", "family"],
    personality: ["traditional", "festive", "welcoming"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["diwali", "toran", "door", "decoration", "festival"]
  },
  {
    name: "Brass Pooja Thali Set",
    description: "Traditional brass thali with diya, incense holder and kumkum container",
    category: "Home Decor",
    priceMin: 600,
    priceMax: 1800,
    interests: ["Home Decor"],
    occasions: ["Diwali", "Festival", "Wedding"],
    relationship: ["family", "partner"],
    personality: ["traditional", "spiritual", "cultured"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["diwali", "pooja", "brass", "thali", "festival"]
  },
  {
    name: "Scented Candle Gift Set Festive",
    description: "Luxury scented candles in festive fragrances with decorative holders",
    category: "Home Decor",
    priceMin: 800,
    priceMax: 2000,
    interests: ["Home Decor"],
    occasions: ["Diwali", "Festival", "Birthday"],
    relationship: ["friend", "family", "colleague", "partner"],
    personality: ["modern", "sophisticated", "festive"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["diwali", "candles", "scented", "gift", "festival"]
  },
  {
    name: "Traditional Sweet Hamper",
    description: "Assorted Indian sweets including ladoo, barfi, and halwa in decorative packaging",
    category: "Food",
    priceMin: 600,
    priceMax: 1800,
    interests: ["Food"],
    occasions: ["Diwali", "Festival", "Birthday"],
    relationship: ["friend", "family", "colleague"],
    personality: ["traditional", "sweet-tooth", "generous"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["diwali", "sweets", "mithai", "hamper", "festival"]
  },
  {
    name: "Decorative Lantern Set (Set of 3)",
    description: "Colorful hanging lanterns with LED lights for festive decoration",
    category: "Home Decor",
    priceMin: 500,
    priceMax: 1500,
    interests: ["Home Decor"],
    occasions: ["Diwali", "Festival"],
    relationship: ["friend", "family"],
    personality: ["festive", "modern", "decorative"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["diwali", "lantern", "decoration", "festival"]
  },
  {
    name: "Gold Plated Coin Lakshmi",
    description: "24K gold plated Lakshmi coin for prosperity and gifting",
    category: "Jewelry",
    priceMin: 1200,
    priceMax: 3500,
    interests: ["Fashion"],
    occasions: ["Diwali", "Festival", "Anniversary"],
    relationship: ["family", "partner"],
    personality: ["traditional", "auspicious", "spiritual"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["diwali", "gold", "coin", "lakshmi", "festival"]
  },
  {
    name: "Decorative Wall Hanging Diwali",
    description: "Handcrafted wall hanging with mirrors and beadwork for festive decoration",
    category: "Home Decor",
    priceMin: 400,
    priceMax: 1200,
    interests: ["Home Decor", "Art"],
    occasions: ["Diwali", "Festival"],
    relationship: ["friend", "family"],
    personality: ["artistic", "traditional", "decorative"],
    affiliateLink: null,
    imageUrl: null,
    tags: ["diwali", "wall-hanging", "decoration", "festival"]
  }
];
